import './js/trucks-slider';
import './js/order-form';
import './js/about-slider';
import './js/team-slider';
import './js/sto-Slider';
import './js/mobile-menu';
import './js/validation';
import './js/order-truck-modal';
import './js/calculate-price-modal';
